from accounts.models import Test

tests=[
    'Hiv Test (HCT, RCT, VCT, PICT)',
    'BS (For mps)',
    'BS (For Microfilaria, Tryps, Leishmania)',
    'BAT',
    'Widal Test',
    'VDRL, RPR, TPHA',
    'H.Pylori Test',
    'Rheumatoid factor test',
    'HBsAg Test',
    'Serum Crag (Cryptococcal antigen)',
    'CD4, & CD4%',
    'Serum HCG Test',
    'Toxoplasmosis',
    'Gonnorhae',
    'Blood culture & Sensitivity',
    'Semen Analysis',
    'HIV RNA PCR (Viral Load)',
    'HVS Gram stain',
    'HVS Culture & Senstivity',
    'CBC',
    'Hb',
    'Sickling Test',
    'ESR',
    'Bleeding Time',
    'Clotting Time',
    'Prothrombine Time',
    'Platelet Count',
    'Blood Grouping',
    'Lymph Zn for AFBs',
    'Lymph Gram stain',
    'Urinalysis',
    'Gram stain',
    'Culture & Senstivity',
    'Urine HCG',
    'Stool analysis (Wet/Iodine- Preparation)',
    'Stool Culture & Senstivity',
    'Modified Zn (For Oocysts)',
    'Sudan III test (For stool Fat)',
    'Sputum Zn for AFBs',
    'Sptum Culture & Senstivity',
    'Brest milk gram stain',
    'Breast milk Culture and Senstivity',
    'Biopsy Gram / Zn stain',
    'KOH + Calcoflour (fungal hypae)',
    'Biopsy Culture & Senstivity',
    'Random Blood Sugars',
    'Fasting Blood Sugars',
    'Renal Functional tests: Sodium, Pottasium, Cloride,Cretine,Urea',
    'Liver functional Tests: GOT,GPT,ALP,Alb,TP,BIL',
    'Pancreatic Functional tests (PFTs): Amylase, Lipase,Glucose',
    'Lipid Profile (LP): Cholesterol, HDL,LDL,Triglycerides'
]